[package]
name = "substreams-solana-tutorial"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = "0.5.0"
substreams-solana = "0.2.0"
prost = "0.11"
num-bigint = "0.4"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"