version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - nestjs-network    
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: node:18
    container_name: nest_app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - nestjs-network  
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run build && npm run start:prod"

networks:
  nestjs-network:
    driver: bridge

volumes:
  pgdata:
