version: '3.1'

services:
  streaming-server:
    build:
      dockerfile: Dockerfile
    ports:
      - 20000:20000
    networks:
      - astralane-network
    depends_on:
      - postgres
    environment:
      ADMIN_SERVER_URL: "http://host.docker.internal:3000"
      GEYSER_URL: "http://host.docker.internal:10000"
      RELAYER_URL: "http://host.docker.internal:11226"
      DB_ADDRESS: "postgres:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432
    networks:
      - astralane-network
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  astralane-network:

