import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import AppNavbar from "@/component/AppNavbar";
import Providers from "./provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Providers>
          <main className="flex">
            <AppNavbar />
            <main className="p-8 w-full max-h-screen overflow-scroll">
              {children}
            </main>
          </main>
        </Providers>
      </body>
    </html>
  );
}
