version: '3.1'

services:
  streaming-server:
    build:
      dockerfile: Dockerfile
    ports:
      - 20000:20000
    networks:
      - astralane-network
    depends_on:
      - postgres
    environment:
      ADMIN_SERVER_URL: "http://host.docker.internal:3000"
      GEYSER_URL: "http://host.docker.internal:10000"
      RELAYER_URL: "http://host.docker.internal:11226"
      DB_ADDRESS: "postgres:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  graphql-service:
    image: node:18
    container_name: nest_app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - /Users/mich/projects/solana/a/astralane-index-graphql-server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "23000:3000"
    networks:
      - nestjs-network
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run build && npm run start:prod"

  postgres:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432
    networks:
      - astralane-network
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  astralane-network:

